### ISSUE TITLE
Expose Busbar app-specific configuration to the environment

### ISSUE THREAD

**Issue by ilyakam** [busbar-io/busbar-server#46]
It's useful to reference the apps' names, environments, and components via an environment variable. I propose the following:

- `BUSBAR_APP` - The `APP` from `busbar create APP [ENV]`
- `BUSBAR_ENV` - The `ENV` from `busbar create APP [ENV]`
- `BUSBAR_COMPONENT` - The `COMPONENT_TYPE` from `busbar logs APPLICATION_CONTAINER ENV [COMPONENT_TYPE]`

**Comment by waldman** [comment]
Taken care on the PR: https://github.com/busbar-io/busbar-server/pull/48/files

**Comment by ilyakam** [comment]
I don't see how this issue is related to Datadog as seen in #48.

**Comment by ilyakam** [comment]
Having read the issue above, I realize that it might have been a bit too brief and therefore unclear. Allow me to clarify with an example:

```
$ busbar create my_app my_env [my options]
» [redacted for brevity]

$ busbar containers my_app my_env
» [NAME=my_app-abc123-web-000-000]

$ busbar ssh my_app-abc123-web-000-000 my_env
root@my_app...:/...# env | grep BUSBAR_APP
» expected = my_app; actual = nothing

root@my_app...:/...# env | grep BUSBAR_ENV
» expected = my_env; actual = nothing

root@my_app...:/...# env | grep BUSBAR_COMPONENT
» expected = web; actual = nothing
```

As you can see, I don't think that accomplishing the request above has anything to do with a third-party event logging service such as Datadog. Please correct me if I'm wrong about this.
